"""
DATA TYPES IN PYTHON
1.Funda mental Data Types
a . int
b. float
c.bool
d.str
2.Complex Data Types        
a.list
b.tuple 
c.set
d.dictionary


"""
# Fundamental Data Types examples
x=10
y=12.45
z=5+6j
print(x,type(x))
print(y,type(y))
print(z,type(z))
f1=12e2
f2=5E3
print(f1,type(f1))
print(f2,type(f2))
a=True
b=False
print(a,type(a))
print(b,type(b))
s1="Hello"
s2='Python Programming' 
print(s1,type(s1))
print(s2,type(s2))

c1=5+4j
c2=complex(2,-3)
print(c1,c2)
print(c1+c2)
print(c1*c2)
print(c1-c2)
print(c1/c2)
print(c1.real)
print(c1.imag)